-- Creacion de la base de datos 
create database Bazar;

-- Para hacer el uso de la base de datos 
use Bazar;

-- Empezamps a crear las tablas 
-- Tabla de Categoria del producto
create table CATPRO (
CATPRODID INT NOT NULL AUTO_INCREMENT,
CATPRONOM VARCHAR(50),
CATPRODES VARCHAR(50),
CATCTCRE  DATETIME,
Constraint PK_Proid primary key (CATPRODID));

-- Tabla inventario de los productos
create table INV_PRO (
INVPROID INT NOT NULL AUTO_INCREMENT,
NVPROCAN VARCHAR(50),
CATCTCRE  DATETIME,
CONSTRAINT PK_INVPROID PRIMARY KEY (INVPROID));

-- Tabla para aplicar algun descuento
CREATE TABLE DESCUENTO (
DESCID  INT NOT NULL AUTO_INCREMENT,
DESCNOM VARCHAR(50),
DESCDES VARCHAR(50),
DESCPOR INT,
DESCACT BOOL,
DESCTCR DATETIME,
CONSTRAINT PK_DESID PRIMARY KEY (DESCID));


-- Tabla de los productos
CREATE TABLE PRODUCTO(
PRODID INT NOT NULL AUTO_INCREMENT,
PRONOM VARCHAR(50),
PRODES VARCHAR(50),
PROSKU VARCHAR(50),
PROCATId INT NOT NULL,
PROINVId INT NOT NULL,
PROPRE DECIMAL,
PRODISId INT,
PROCREAT DATETIME,
PRODMODI DATETIME,
PRODELET DATETIME,
CONSTRAINT PK_ProID PRIMARY KEY (PRODID),
CONSTRAINT FK_CatId FOREIGN KEY (PROCATId) REFERENCES CATPRO(CATPRODID),
CONSTRAINT FK_InvId FOREIGN KEY (PROINVId) REFERENCES INV_PRO(INVPROID),
CONSTRAINT FK_DesId FOREIGN KEY (PRODISId) REFERENCES DESCUENTO(DESCID));
