-- Creacion de la base de datos 
create database Bazar;

-- Para hacer el uso de la base de datos 
use Bazar;

-- Empezamos a crear las tablas 
-- Tabla de Categoria del producto
create table CATPRO (
CATPRODID INT NOT NULL AUTO_INCREMENT,
CATPRONOM VARCHAR(50),
CATPRODES VARCHAR(50),
CATCTCRE  DATETIME,
Constraint PK_Proid primary key (CATPRODID));

-- Tabla inventario de los productos
create table INV_PRO (
INVPROID INT NOT NULL AUTO_INCREMENT,
INVPROCA VARCHAR(50),
INVPRCRE  DATETIME,
INVPRMOD  DATETIME,
INVPRDEL  DATETIME,
CONSTRAINT PK_INVPROID PRIMARY KEY (INVPROID));

-- Tabla para aplicar algun descuento
CREATE TABLE DESCUENTO (
DESCID  INT NOT NULL AUTO_INCREMENT,
DESCNOM VARCHAR(50),
DESCDES VARCHAR(50),
DESCPOR INT,
DESCACT BOOL,
DESCTCR DATETIME,
CONSTRAINT PK_DESID PRIMARY KEY (DESCID));


-- Tabla de los productos
CREATE TABLE PRODUCTO(
PRODID INT NOT NULL AUTO_INCREMENT,
PRONOM VARCHAR(50),
PRODES VARCHAR(50),
PROSKU VARCHAR(50),
PROCATId INT NOT NULL,
PROINVId INT NOT NULL,
PROPRE DECIMAL,
PRODISId INT,
PROCREAT DATETIME,
PRODMODI DATETIME,
PRODELET DATETIME,
CONSTRAINT PK_ProID PRIMARY KEY (PRODID),
CONSTRAINT FK_CatId FOREIGN KEY (PROCATId) REFERENCES CATPRO(CATPRODID),
CONSTRAINT FK_InvId FOREIGN KEY (PROINVId) REFERENCES INV_PRO(INVPROID),
CONSTRAINT FK_DesId FOREIGN KEY (PRODISId) REFERENCES DESCUENTO(DESCID));



-- Tabla de usuario 
CREATE TABLE USUARIO (
USERID INT NOT NULL AUTO_INCREMENT,
USUARI VARCHAR(20) NOT NULL,
USPASS VARCHAR(20) NOT NULL,
USNOMB VARCHAR(20) NOT NULL,
USAPPT VARCHAR(20) NOT NULL,
USAPMT VARCHAR(20),
USTELO VARCHAR(10),
USEMAI VARCHAR(20) NOT NULL,
USCREA DATETIME,
USMODI DATETIME,
CONSTRAINT PK_ProID PRIMARY KEY (USERID));

-- Tabla de la direccion de el usuario 
CREATE TABLE US_DIRE(
USDIRID INT NOT NULL AUTO_INCREMENT,
USDUSID INT NOT NULL,
USDDIR1 VARCHAR(50),
USDDIR2 VARCHAR(50),
USDCIUD VARCHAR(20),
USDIRCP INT(5),
USDIRTE VARCHAR(10),
USDIRMO VARCHAR(10),
CONSTRAINT PK_IdDir PRIMARY KEY (USDIRID),
CONSTRAINT FK_Usrid FOREIGN KEY (USDUSID) REFERENCES USUARIO(USERID));

-- Tabla pago del usuario
CREATE TABLE PAGOUSUARIO (
PAIDID INT NOT NULL AUTO_INCREMENT,
PAYUSID INT NOT NULL,
PAYTYPE VARCHAR(50),
PAYPROV VARCHAR(20),
PAYTARJ INT(16),
PAYEXPI INT(4),
PAYCODE INT(3),
CONSTRAINT PK_PaId PRIMARY KEY (PAIDID),
CONSTRAINT FK_Payus FOREIGN KEY (PAYUSID) REFERENCES USUARIO(USERID)
);

-- TABLA DE SESION DE SHOPPING
CREATE TABLE SHOPSS(
SHSEID INT NOT NULL AUTO_INCREMENT,
SSUSID INT NOT NULL,
SSTOTA DECIMAL(6,2),
USCREA DATETIME,
USMODI DATETIME,
CONSTRAINT PK_SheID PRIMARY KEY (SHSEID),
CONSTRAINT FK_ShSID FOREIGN KEY (SSUSID) REFERENCES USUARIO(USERID)); 

-- Tabla carrito de compras 
CREATE TABLE CARRITO(
CARRIID INT NOT NULL AUTO_INCREMENT,
CARSSID INT NOT NULL,
CARPRID INT NOT NULL,
CARCATI INT,
USCREA DATETIME,
USMODI DATETIME,
CONSTRAINT PK_CarID PRIMARY KEY (CARRIID),
CONSTRAINT FK_CarSS FOREIGN KEY (CARSSID) REFERENCES SHOPSS(SHSEID),
CONSTRAINT FK_CaPID FOREIGN KEY (CARPRID) REFERENCES PRODUCTO(PRODID));

-- DETALES DE LA ORDEN 
-- TABLA DEL DETALLE DEL PAGO
CREATE TABLE PAYDETALLES(
PAYDETID INT NOT NULL AUTO_INCREMENT,
PAYORDID INT,
PAYMONTO DECIMAL(6,2),
PAYPROVE VARCHAR(20),
PAYSTATU VARCHAR(20),
PAYCREA DATETIME,
PAYMODI DATETIME,
CONSTRAINT PK_Pag PRIMARY KEY (PAYDETID));

-- TABLA DE DETALLE DE LA ORDEN 
CREATE TABLE ORDDET(
ORDDETALID INT NOT NULL AUTO_INCREMENT,
ORDDETUSID INT NOT NULL,
ORDDETOTAL DECIMAL(6,2),
ORDDEPDEID INT NOT NULL,
ORDDECREA DATETIME,
ORDDEMODI DATETIME,
CONSTRAINT PK_DetID PRIMARY KEY (ORDDETALID),
CONSTRAINT FK_UseID FOREIGN KEY (ORDDETUSID) REFERENCES USUARIO(USERID),
CONSTRAINT FK_PagID FOREIGN KEY (ORDDEPDEID) REFERENCES PAYDETALLES(PAYDETID));

-- TABLA ORDEN ITEM
CREATE TABLE ORDENITEM(
ORDITID INT NOT NULL AUTO_INCREMENT,
ORDITDETID INT NOT NULL,
ORDITPROID INT NOT NULL,
ORDITCANT INT,
ORDITCREA DATETIME,
ORDITMODI DATETIME,
CONSTRAINT PK_ItID PRIMARY KEY  (ORDITID),
CONSTRAINT FK_OrdID FOREIGN KEY (ORDITDETID) REFERENCES ORDDET(ORDDETALID),
CONSTRAINT FK_ProID FOREIGN KEY (ORDITPROID) REFERENCES PRODUCTO(PRODID));
